## MLA
- Numpy
- Pandas
- Seaborn/Matplotlib
- Linear Regression
- Logistic Regression

## Numpy

- Numpy stands for numerical python
- Building block for many other libraries like Pandas, Matplotlib etc

In [4]:
#Import library
import numpy as np

In [5]:
#!pip install numpy
#pip install numpy

In [6]:
np.__version__
#import numpy==1.16 
#!pip install --force-reinstall numpy==1.20

'1.26.4'

## Data types available in numpy - Array
- Scalars
- Vectors or 1-d arrays
- Matrices or 2-d arrays
- Higher dimensional arrays

In [8]:
#Scalar - That doesn't have direction and has only magnitude
# np.array is the function used to create a numpy array
arr1 = np.array(10)

In [9]:
arr1

array(10)

In [10]:
type(arr1)  #datatype of the variable as a whole

numpy.ndarray

In [11]:
# Attributes of a numpy array
#dtype  - datatype of elements in it.
#ndim - Dimension of the array
#size - No. of the elements in the array
#shape - how many elements in each dimension

In [12]:
#Creating a 1-d array using a list
arr2 = np.array([1,2,3,4])

In [13]:
arr2

array([1, 2, 3, 4])

In [14]:
# Creating a 1-d array using a tuple
arr2 = np.array((2,2,3,4))

In [15]:
arr2

array([2, 2, 3, 4])

In [16]:
#Creating a 2-d array - Matrix
arr3 = np.array([[1,2,3,4],[2,3,4,5]])

In [17]:
arr3

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [18]:
#arr1 is a scalar. arr1 = 10
arr1.dtype  #datatype of elements inside the array

dtype('int32')

In [19]:
arr4 = np.array([1,2,3,1.234])
print(type(arr4), arr4.dtype)

<class 'numpy.ndarray'> float64


In [20]:
arr1.ndim #no. of the dimensions present in the array

0

In [21]:
arr1.shape #Gives how the elements are layered in each dimension

()

In [22]:
arr1.size #total number of elements in the array

1

In [23]:
a = [[1,2,3],[4,5,6],[7,6,5]]
len(a)

3

In [24]:
b = np.array(a)
print(b.size, b.shape)

9 (3, 3)


In [25]:
print(arr2,type(arr2))

[2 2 3 4] <class 'numpy.ndarray'>


In [26]:
print('datatypes of elements:', arr2.dtype, 'dimension:', arr2.ndim, 'shape:', arr2.shape,'size:' ,arr2.size)

datatypes of elements: int32 dimension: 1 shape: (4,) size: 4


In [27]:
print(arr3,type(arr3))

[[1 2 3 4]
 [2 3 4 5]] <class 'numpy.ndarray'>


In [28]:
print('datatypes of elements:', arr3.dtype, 'dimension:', arr3.ndim, 'shape:', arr3.shape,'size:' ,arr3.size)

datatypes of elements: int32 dimension: 2 shape: (2, 4) size: 8


In [29]:
# A 2-d array is called a matrix

In [30]:
arr = np.array([[[[[[1,2]]]]]])

In [31]:
print(arr,type(arr),'datatypes of elements:', arr.dtype, 'dimension:', arr.ndim, 'shape:', arr.shape,'size:' ,arr.size)

[[[[[[1 2]]]]]] <class 'numpy.ndarray'> datatypes of elements: int32 dimension: 6 shape: (1, 1, 1, 1, 1, 2) size: 2


In [32]:
arr = np.array([[[1,2,3,4],[2,3,4,5],[1,2,3,4]],[[4,5,6,7],[8,9,7,6],[5,4,3,2]]])
arr

array([[[1, 2, 3, 4],
        [2, 3, 4, 5],
        [1, 2, 3, 4]],

       [[4, 5, 6, 7],
        [8, 9, 7, 6],
        [5, 4, 3, 2]]])

In [33]:
print(arr,type(arr),'datatypes of elements:', arr.dtype, 'dimension:', arr.ndim, 'shape:', arr.shape,'size:' ,arr.size)

[[[1 2 3 4]
  [2 3 4 5]
  [1 2 3 4]]

 [[4 5 6 7]
  [8 9 7 6]
  [5 4 3 2]]] <class 'numpy.ndarray'> datatypes of elements: int32 dimension: 3 shape: (2, 3, 4) size: 24


In [34]:
arr = np.array([[[1,2],[2,3]],[[4,5],[6,7]]])

In [35]:
print(arr,type(arr),'datatypes of elements:', arr.dtype, 'dimension:', arr.ndim, 'shape:', arr.shape,'size:' ,arr.size)

[[[1 2]
  [2 3]]

 [[4 5]
  [6 7]]] <class 'numpy.ndarray'> datatypes of elements: int32 dimension: 3 shape: (2, 2, 2) size: 8


In [36]:
arr = np.array({1,2})

In [37]:
arr

array({1, 2}, dtype=object)

In [38]:
arr = np.array({'A':1,'B':2})
arr

array({'A': 1, 'B': 2}, dtype=object)

In [39]:
print(arr,type(arr),'datatypes of elements:', arr.dtype, 'dimension:', arr.ndim, 'shape:', arr.shape,'size:' ,arr.size)

{'A': 1, 'B': 2} <class 'numpy.ndarray'> datatypes of elements: object dimension: 0 shape: () size: 1


### Reshape function: Lets you change the shape of array

In [41]:
arr = np.array([1,2,3])

In [42]:
print(arr,'dimension:', arr.ndim, 'shape:', arr.shape,'size:' ,arr.size)

[1 2 3] dimension: 1 shape: (3,) size: 3


In [43]:
arr.reshape((1,1,1,3,1,1,1))

array([[[[[[[1]]],


          [[[2]]],


          [[[3]]]]]]])

In [44]:
arr.reshape((1,3))

array([[1, 2, 3]])

In [45]:
arr.reshape((3,1))

array([[1],
       [2],
       [3]])

In [46]:
arr

array([1, 2, 3])

In [47]:
arr = np.array([1,2,3,4])
print(arr,'dimension:', arr.ndim, 'shape:', arr.shape,'size:' ,arr.size)

[1 2 3 4] dimension: 1 shape: (4,) size: 4


In [48]:
arr1 = arr.reshape((2,2))

In [49]:
print(arr1,'dimension:', arr1.ndim, 'shape:', arr1.shape,'size:' ,arr1.size)

[[1 2]
 [3 4]] dimension: 2 shape: (2, 2) size: 4


In [50]:
arr = np.array([1,2,3,4])

In [51]:
arr2 = arr.reshape((1,2,2,1))
print(arr2,'dimension:', arr2.ndim, 'shape:', arr2.shape,'size:' ,arr2.size)

[[[[1]
   [2]]

  [[3]
   [4]]]] dimension: 4 shape: (1, 2, 2, 1) size: 4


### Built in arrays:
- arange - a 1-d array with uniformly spaced numbers between a start and stop value. Integers
  - np.arange(start,stop,step)
  - Can be used in combination with a reshape function to create an array of any dimension. 
- zeros, ones - zero  matrix and ones matrix
  - np.zeros(shape tuple,dtype)
  - np.ones(shape tuple,dtype)
- linspace - Generate a count of samples between start and stop values
  - np.linspace(start,stop,count)
  - Stop is inclusive
- eye - Create an identity matrix
  - (defaults square matrix, can be made as rectangular matrix)

In [53]:
# np.arange(start,stop,step)  : Start - defaults to 0, step value defaults to 1, stop is exclusive
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [54]:
arr = np.arange(2,15,0.5)
arr

array([ 2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,
        7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5, 12. , 12.5,
       13. , 13.5, 14. , 14.5])

In [55]:
arr = np.arange(-1,6,-1)
arr

array([], dtype=int32)

In [56]:
arr = np.arange(-1,-6,-1)
arr

array([-1, -2, -3, -4, -5])

In [57]:
np.arange(2,40,7)
arr = np.arange(2,30,3).reshape((5,2))
arr

array([[ 2,  5],
       [ 8, 11],
       [14, 17],
       [20, 23],
       [26, 29]])

In [58]:
arr = np.arange(1.4,3.7,0.58)
arr

array([1.4 , 1.98, 2.56, 3.14])

In [59]:
#arr = np.zeros(shape, datatype)
arr = np.zeros((3,2),dtype=int)
arr

array([[0, 0],
       [0, 0],
       [0, 0]])

In [60]:
arr = np.zeros((4,5,6),dtype=float)
arr

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [61]:
#np.ones(shape tuple,dtype)
arr= np.ones(4,dtype=int)
arr

array([1, 1, 1, 1])

In [62]:
arr= np.ones((4,),dtype=int)
arr

array([1, 1, 1, 1])

In [63]:
arr = np.ones((4,5,6),dtype=float)
arr

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [64]:
arr = np.linspace(2,40,23)
arr

array([ 2.        ,  3.72727273,  5.45454545,  7.18181818,  8.90909091,
       10.63636364, 12.36363636, 14.09090909, 15.81818182, 17.54545455,
       19.27272727, 21.        , 22.72727273, 24.45454545, 26.18181818,
       27.90909091, 29.63636364, 31.36363636, 33.09090909, 34.81818182,
       36.54545455, 38.27272727, 40.        ])

In [65]:
#np.linspace(start,stop,count) start defaults to 0, count defaults to 50, stop is inclusive, endpoint=False makes stop exclusive
arr = np.linspace(2,40,23,endpoint=False,retstep=True)
arr

(array([ 2.        ,  3.65217391,  5.30434783,  6.95652174,  8.60869565,
        10.26086957, 11.91304348, 13.56521739, 15.2173913 , 16.86956522,
        18.52173913, 20.17391304, 21.82608696, 23.47826087, 25.13043478,
        26.7826087 , 28.43478261, 30.08695652, 31.73913043, 33.39130435,
        35.04347826, 36.69565217, 38.34782609]),
 1.6521739130434783)

In [66]:
arr = np.linspace(2,40,20,retstep=True, dtype='int')
arr

(array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40]),
 2.0)

In [67]:
#np.eye(size, offset)
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [68]:
np.eye(5,k=1,dtype=int)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [69]:
np.eye(5,k=-1,dtype=int)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]])

### Operations on numpy arrays - Broadcasting 
- Broadcasting is a feature of numpy that allows operations on elements of array without needing a loop.
- Stretching is a form of broadcasting where matrices of different dimensions can be operated on.
  

In [71]:
arr = np.array([[1,2,3,4,5],[3,4,5,6,7]])

In [137]:
arr

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7]])

In [142]:
arr+1
#arr = arr+1

array([[2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8]])

In [169]:
arr

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7]])

In [171]:
arr*2

array([[ 2,  4,  6,  8, 10],
       [ 6,  8, 10, 12, 14]])

In [173]:
arr*arr

array([[ 1,  4,  9, 16, 25],
       [ 9, 16, 25, 36, 49]])

In [144]:
# Stretching
arr

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7]])

In [146]:
arr2 = np.array([10,20,30,40,50])
arr2

array([10, 20, 30, 40, 50])

In [193]:
arr+arr2

array([[11, 22, 33, 44, 55],
       [13, 24, 35, 46, 57]])

In [195]:
arr3 = np.array([1,2,3,4,5,6,7])

In [189]:
arr+arr3

ValueError: operands could not be broadcast together with shapes (2,5) (7,) 

In [197]:
arr**3

array([[  1,   8,  27,  64, 125],
       [ 27,  64, 125, 216, 343]], dtype=int32)

### Random module
#### Functions 
- rand: Generate a float array of chosen dimension of values between 0 and 1
- randn: Generates a array of chosen dimension with values that belong a Standard normal distribution
- randint: Generates a array of integers between chosen values

In [156]:
# rand
#from numpy import random
np.random.rand(2,3,4)   # 0 is inclusive, 1 is exclusive

array([[[0.86080866, 0.06732715, 0.67412532, 0.09538981],
        [0.31874214, 0.95453203, 0.45308577, 0.31054611],
        [0.23598214, 0.22500585, 0.84593815, 0.86467432]],

       [[0.75509641, 0.28325667, 0.69153388, 0.52269038],
        [0.71957886, 0.62821101, 0.01120521, 0.10267584],
        [0.12676955, 0.07503653, 0.68351159, 0.102524  ]]])

In [158]:
np.random.randn(2,5)

array([[ 0.42680202, -1.92608266, -0.00833434,  0.8768039 ,  0.40194857],
       [ 0.58838132,  0.47211151, -0.46272778,  1.46586739, -0.84895849]])

In [209]:
#np.random.randint(low,high,count)
np.random.randint(2,50,12)

array([32,  7, 17, 13, 37, 40,  9,  2, 30, 15, 26, 17])

In [211]:
np.random.randint(1,7,40)

array([1, 6, 1, 2, 5, 5, 2, 6, 3, 6, 2, 1, 6, 2, 4, 4, 4, 6, 5, 2, 4, 5,
       5, 4, 5, 6, 3, 4, 6, 1, 2, 2, 2, 3, 1, 5, 4, 6, 2, 6])

In [213]:
np.random.randint(2,10,(2,5))

array([[6, 5, 9, 9, 4],
       [8, 6, 3, 7, 2]])

### Properties of numpy arrays
-min, max, argmin, argmax, mean, median

In [160]:
arr

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7]])

In [237]:
#arr.min()
np.min(arr)

1

In [239]:
#arr.max()
np.max(arr)

7

In [241]:
#arr.argmin()
np.argmin(arr)

0

In [243]:
#arr.argmax()
np.argmax(arr)

9

In [ ]:
#arr.mean()
np.mean(arr)

In [ ]:
np.median(arr)


In [245]:
#np.where - lets you find the element meeting a condition
arr = np.array([5,6,7,3,2,1,8,9,10])

In [247]:
np.where(arr>4)

(array([0, 1, 2, 6, 7, 8], dtype=int64),)

In [249]:
np.where(arr%2==0)

(array([1, 4, 6, 8], dtype=int64),)

In [253]:
arr[np.where(arr%2==0)]

array([ 6,  2,  8, 10])

In [257]:
print(np.where(arr>7),'\n',arr[np.where(arr>7)])

(array([6, 7, 8], dtype=int64),) 
 [ 8  9 10]


In [164]:
a = np.array([[1,2,3,4,5],[2,3,4,5,6]])
np.where(a%2==0)

(array([0, 0, 1, 1, 1], dtype=int64), array([1, 3, 0, 2, 4], dtype=int64))

In [174]:
np.where((a.reshape((-1,)))%2==0)

(array([1, 3, 5, 7, 9], dtype=int64),)

### Indexing a numpy array
- arr[index]
- arr[d0index][d1index]...

In [269]:
arr

array([ 5,  6,  7,  3,  2,  1,  8,  9, 10])

In [271]:
len([1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,4,6,8,9,0,2,3,5,11])

30

In [273]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10,1,4,6,8,9,0,2,3,5,11]).reshape(2,5,3)

In [275]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10,  1],
        [ 4,  6,  8],
        [ 9,  0,  2],
        [ 3,  5, 11]]])

In [279]:
arr[0,1,2]

6

In [277]:
arr[0][1][1]

5

In [281]:
arr[0][1][0:1]

array([4])

In [283]:
arr[0][1]

array([4, 5, 6])

In [293]:
arr[0][0][1]

2

In [289]:
arr[0,0:1]

array([[1, 2, 3]])

In [291]:
arr[0,0:1,1]

array([2])

In [285]:
arr[0][0:1]

array([[1, 2, 3]])

In [297]:
arr[0][0:1][0,1]

2

In [ ]:
print(arr[0][0:1][0,0:2])

#### Understanding notation for slicing

In [299]:
print(arr[0][1])

[4 5 6]


In [301]:
print(arr[0][1:2])

[[4 5 6]]


In [303]:
print(arr[0,1:2])

[[4 5 6]]


In [305]:
print(arr[0][1][1])

5


In [307]:
print(arr[0][1:2][1:2])

[]


In [309]:
print(arr[0,1:2,1:2])

[[5]]


In [311]:
arr[0][0:1][0:2]

array([[1, 2, 3]])

In [ ]:
arr

### Copy vs View

In [176]:
arr = np.array([1,2,3])

In [178]:
arr+1

array([2, 3, 4])

In [180]:
arr

array([1, 2, 3])

In [319]:
arr1 = arr

In [321]:
arr1

array([1, 2, 3])

In [ ]:
arr

In [323]:
arr[2] = 10

In [325]:
arr

array([ 1,  2, 10])

In [327]:
arr1

array([ 1,  2, 10])

In [329]:
arr1[1] = 20

In [331]:
arr1

array([ 1, 20, 10])

In [333]:
arr

array([ 1, 20, 10])

In [ ]:
arr = np.array([1,2,3])
arr

In [337]:
arr = np.array([1,2,3])
arr2 = arr.copy()
arr2

array([1, 2, 3])

In [339]:
arr[2] = 10
arr

array([ 1,  2, 10])

In [341]:
arr2

array([1, 2, 3])

In [ ]:
arr3 = arr.view()

In [ ]:
import statistics
a = [1,2,3,4,5,1,2,3,4,5,1,2,3,4,5,2,3,2,3]
statistics.multimode(a)

In [182]:
a = [1,2,3,4]

In [217]:
type(a)

list

In [227]:
a = []
for i in range(10):
    a.append(int(input('Enter a number')))
b = np.array(a)

Enter a number 1
Enter a number 2
Enter a number 3
Enter a number 4
Enter a number 5
Enter a number 6
Enter a number 3
Enter a number 4
Enter a number 5
Enter a number 3


In [229]:
b

array([1, 2, 3, 4, 5, 6, 3, 4, 5, 3])

In [231]:
a = input('Enter a list:')
b = list(a)

Enter a list: [1,2,3]


In [233]:
b

['[', '1', ',', '2', ',', '3', ']']

In [225]:
type(b)

numpy.ndarray